### ISSUE TITLE
依然有问题，不知道为啥

### ISSUE THREAD

**Issue by cadaeibf1** [cc004/pcrjjc2#111]
[2022-12-07 02:13:35,084 竞技场推送] ERROR: <class 'AttributeError'> occured when wrapper handling message 1624892920.
[2022-12-07 02:13:35,084 竞技场推送] ERROR: module 'hoshino.util' has no attribute 'filt_message'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Hoshinobot\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\Hoshinobot\HoshinoBot\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\Hoshinobot\HoshinoBot\hoshino\modules\pcrjjc2\__init__.py", line 269, in on_query_arena
    f'''昵称：{util.filt_message(str(res['user_info']["user_name"]))}
AttributeError: module 'hoshino.util' has no attribute 'filt_message'
[2022-12-07 02:13:35,099 nonebot] INFO: Message 1624892920 is ignored: Handled by RexTrigger of Hoshino

**Comment by cc004** [comment]
升级hoshino
