### ISSUE TITLE
各位老大，请教下geetest功能传参错误该如何解决

### ISSUE THREAD

**Issue by OracleL1nk** [cc004/pcrjjc2#129]
在首次传入实际IP的时候出现了call_action()传参数量溢出的错误，后边就是无尽的重复蓝图名称冲突。

**Comment by OracleL1nk** [comment]
```
[2023-07-31 21:53:42,920 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.aiorequests", error: call_action() takes 2 positional arguments but 3 were given
[2023-07-31 21:53:42,920 nonebot] ERROR: call_action() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 35, in <module>
    async def get_real_ip() -> str:
TypeError: call_action() takes 2 positional arguments but 3 were given
[2023-07-31 21:53:42,920 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.bsgamesdk", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,920 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,920 nonebot] INFO: Succeeded to import "hoshino.modules.pcrjjc2.create_img"
[2023-07-31 21:53:42,920 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.geetest", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,943 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.jjchistory", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.pcrclient", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.pcrclient_1", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,949 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,967 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.rsacr", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,967 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,967 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.safeservice", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,967 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\__init__.py", line 18, in <module>
    from .geetest import get_public_address
  File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 31, in <module>
    bot_.server_app.register_blueprint(geetest_validate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1420, in register_blueprint
    raise RuntimeError(
RuntimeError: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
```

**Comment by OracleL1nk** [comment]
目前我是去掉了错误处理的注释，但还是没搞明白哪出了问题
```

@bot_.on_startup
async def get_real_ip() -> str:
#def get_real_ip() -> str:
    public_address = f"127.0.0.1:{config.PORT}"
    try:
        if config.public_address:
            public_address = config.public_address
            printf("comfirm pa")
        elif config.IP:
            public_address = f"{config.IP}:{config.PORT}"
            printf("comfirm ip")
    except AttributeError:
        from . import send_to_admin
        try:
            resp = await aiorequests.get(url="https://4.ipw.cn", timeout=3)
            real_ip = await resp.text
            public_address = f"{real_ip}:{config.PORT}"
            hoshino.logger.info(f"using fetched real ip as public address: {public_address}")
            await sendToAdmin(f"成功获取公网IP：{real_ip}\n注意：本IP仅在你有公网IP时才有效！如果你没有公网IP，请使用127.0.0.1作为你的IP！")
        except Exception as e:
            hoshino.logger.error(f"获取公网IP失败\n{e}")
            await sendToAdmin(f"获取公网IP失败，使用默认IP\n{e}")
        #pass
    hoshino.logger.info(f"current public address: {public_address}")
    printf(f"current public address: {public_address}")
    return public_address
```

**Comment by OracleL1nk** [comment]
学艺不精，劳烦各位大佬了。

**Comment by cca2878** [comment]
检查request库版本

**Comment by OracleL1nk** [comment]
使用的是main分支，我的nonebot是1.6.0版本，我也很奇怪，搜索过整个项目，也没找到call_action定义在哪。
那蓝图重复注册的错误是因为首次获取真实ip失败导致的吗？
```
File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 35, in <module>
    async def get_real_ip() -> str:
TypeError: call_action() takes 2 positional arguments but 3 were given
[2023-07-31 21:53:42,920 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.bsgamesdk", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
[2023-07-31 21:53:42,920 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
Traceback (most recent call last):
```

**Comment by cca2878** [comment]
> 使用的是main分支，我的nonebot是1.6.0版本，我也很奇怪，搜索过整个项目，也没找到call_action定义在哪。 那蓝图重复注册的错误是因为首次获取真实ip失败导致的吗？
> 
> ```
> File "C:\Users\Administrator\Desktop\Hoshino\hoshino\modules\pcrjjc2\geetest.py", line 35, in <module>
>     async def get_real_ip() -> str:
> TypeError: call_action() takes 2 positional arguments but 3 were given
> [2023-07-31 21:53:42,920 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc2.bsgamesdk", error: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
> [2023-07-31 21:53:42,920 nonebot] ERROR: Blueprint name 'geetest_validate' is already registered by <quart.blueprints.Blueprint object at 0x000001A629F87E20>. Blueprints must have unique names
> Traceback (most recent call last):
> ```

call_action是aiocqhttp库中的函数。蓝图错误的原因是之前的出错导致validate实例未销毁，无需理会。

**Comment by OracleL1nk** [comment]
更新nonebot至1.8.4，问题解决，谢谢大佬
