### ISSUE TITLE
详细查询图片发送失败

### ISSUE THREAD

**Issue by SonderXiaoming** [cc004/pcrjjc2#65]
报错如下
[2022-02-25 09:50:13,919 竞技场推送] INFO: 开始生成竞技场查询图片...
[2022-02-25 09:50:13,966 竞技场推送] ERROR: <class 'AttributeError'> occured when wrapper handling message 270570335.
[2022-02-25 09:50:13,966 竞技场推送] ERROR: 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\huannai\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\huannai\HoshinoBot\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\huannai\HoshinoBot\hoshino\modules\pcrjjc2\__init__.py", line 206, in on_query_arena_all
    result_image = pic2b64(result_image) # 转base64发送，不用将图片存本地
  File "C:\Users\Administrator\Desktop\huannai\HoshinoBot\hoshino\util\__init__.py", line 67, in pic2b64
    pic.save(buf, format='PNG')
AttributeError: 'NoneType' object has no attribute 'save'

好像是星乃的until中save出了问题，但我不知道如何修复

**Comment by CYDXDianXian** [comment]
问题已解决，请更新后再试。
若你已经安装依赖，大概率会出现 #66 这种问题，需要按如下方法操作：
```
pip uninstall msgpack

pip install msgpack==1.0.2
```

**Comment by CYDXDianXian** [comment]
现在你那边正常了么，如果还有问题欢迎继续反馈~
