### ISSUE TITLE
有没有大佬知道这是什么问题

### ISSUE THREAD

**Issue by Ratten-fanger** [cc004/pcrjjc2#71]
[2022-03-01 15:29:03,448 竞技场推送] ERROR: <class 'TypeError'> occured when wrapper handling message -527960032.
[2022-03-01 15:29:03,448 竞技场推送] ERROR: __init__() got an unexpected keyword argument 'strict_map_key'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\__init__.py", line 172, in on_query_arena
    res = await query(id)
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\__init__.py", line 105, in query
    await client.login()
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\pcrclient.py", line 192, in login
    lres = await self.callapi('/tool/sdk_login', {
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\pcrclient.py", line 140, in callapi
    response = pcrclient.unpack(response)[0] if crypted else loads(response)
  File "C:\Users\Administrator\Desktop\coolQ\HoshinoBot\hoshino\modules\pcrjjc2\pcrclient.py", line 124, in unpack
    return unpackb(dec[:-dec[-1]],
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\msgpack\fallback.py", line 118, in unpackb
    unpacker = Unpacker(None, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict_map_key'

**Comment by CYDXDianXian** [comment]
依赖问题，需要将msgpack回滚到1.0.2版本，按如下方法操作：
```
pip uninstall msgpack

pip install msgpack==1.0.2
```
