### ISSUE TITLE
请问这个是哪里出了问题？

### ISSUE THREAD

**Issue by yfsunrise** [cc004/pcrjjc2#92]
[2022-06-09 10:54:09,513 竞技场推送] INFO: 开始生成竞技场查询图片...
[2022-06-09 10:54:09,547 chara] INFO: Downloading chara icon from https://redive.estertion.win/icon/unit/107561.webp
[2022-06-09 10:54:11,275 竞技场推送] ERROR: <class 'FileNotFoundError'> occured when wrapper handling message 723046859.
[2022-06-09 10:54:13,490 竞技场推送] ERROR: [Errno 2] No such file or directory: '../res/img\\priconne\\unit\\icon_unit_107561.png'
Traceback (most recent call last):
  File "D:\Program Files\Hoshino_XCW\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\__init__.py", line 253, in on_query_arena_all
    result_image = await generate_info_pic(res, uid)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 259, in generate_info_pic
    return await run_sync_func(_generate_info_pic_internal, *args, **kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 49, in _generate_info_pic_internal
    pic_dir = chara.fromid(id_favorite).icon.path
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\priconne\chara.py", line 148, in icon
    download_chara_icon(self.id, 6)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\priconne\chara.py", line 118, in download_chara_icon
    img.save(save_path)
  File "D:\Program Files\Python\lib\site-packages\PIL\Image.py", line 2209, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../res/img\\priconne\\unit\\icon_unit_107561.png'

**Comment by CYDXDianXian** [comment]
缺少了头像资源文件，运行一下`...HoshinoBot\res\img\priconne\spider.py`爬虫程序爬取一下头像

**Comment by yfsunrise** [comment]
[2022-06-09 11:04:50,729 竞技场推送] INFO: 开始生成竞技场查询图片...
[2022-06-09 11:04:50,750 竞技场推送] ERROR: <class 'RuntimeError'> occured when wrapper handling message -1127610301.
[2022-06-09 11:04:50,750 竞技场推送] ERROR: no running event loop
Traceback (most recent call last):
  File "D:\Program Files\Hoshino_XCW\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\__init__.py", line 253, in on_query_arena_all
    result_image = await generate_info_pic(res, uid)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 259, in generate_info_pic
    return await run_sync_func(_generate_info_pic_internal, *args, **kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 49, in _generate_info_pic_internal
    pic_dir = chara.fromid(id_favorite).icon.path
  File "D:\Program Files\Hoshino_XCW\hoshino\modules\priconne\chara.py", line 159, in icon
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop

**Comment by yfsunrise** [comment]
我换了一个priconne，现在报错变成这个

**Comment by yfsunrise** [comment]
已解决 感谢

**Comment by Baninn** [comment]
> [2022-06-09 11:04:50,729 竞技场推送] INFO: 开始生成竞技场查询图片... [2022-06-09 11:04:50,750 竞技场推送] ERROR: <class 'RuntimeError'> occured when wrapper handling message -1127610301. [2022-06-09 11:04:50,750 竞技场推送] ERROR: no running event loop Traceback (most recent call last): File "D:\Program Files\Hoshino_XCW\hoshino\msghandler.py", line 28, in handle_message await service_func.func(bot, event) File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper return await func(*args, **kwargs) File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2__init__.py", line 253, in on_query_arena_all result_image = await generate_info_pic(res, uid) File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 259, in generate_info_pic return await run_sync_func(_generate_info_pic_internal, *args, **kwargs) File "D:\Program Files\Hoshino_XCW\hoshino\aiorequests.py", line 10, in run_sync_func return await asyncio.get_event_loop().run_in_executor( File "D:\Program Files\Python\lib\concurrent\futures\thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "D:\Program Files\Hoshino_XCW\hoshino\modules\pcrjjc2\create_img.py", line 49, in _generate_info_pic_internal pic_dir = chara.fromid(id_favorite).icon.path File "D:\Program Files\Hoshino_XCW\hoshino\modules\priconne\chara.py", line 159, in icon loop = asyncio.get_running_loop() RuntimeError: no running event loop

我也是这个，请问是怎么解决的

**Comment by CYDXDianXian** [comment]
@Baninn 去这里下载res资源包：https://github.com/cc004/pcrjjc2/releases/tag/hoshinobot-res

**Comment by Baninn** [comment]
成功了，非常感谢
